"""Append refinement proposals to OPEN_PROPOSALS.md + grammar_proposals (§9.1).

Cross-repo contract (QuantIQ D297, ``forge-proposals/v1``):

* Line 1 of OPEN_PROPOSALS.md MUST be ``# contract: forge-proposals/v1``.
* Each proposal is a YAML mapping document separated by ``---``.
* ``status: PENDING`` is emitted natively (downstream code no longer
  has to hand-insert a STATUS field when the operator approves).
* The ``evidence`` field is a native YAML mapping, not a stringified
  JSON blob (the legacy ``evidence_json`` field is renamed).

Atomic write: each append goes through ``OPEN_PROPOSALS.md.tmp`` then
``os.rename()`` so a partial write can never corrupt the file
mid-edit. Forge is a single-writer service (one ``forge.service``
unit), so the read-modify-write pattern is safe.

D024/D5: every Phase 5 proposal (tighten or loosen) is appended to
``OPEN_PROPOSALS.md`` AND inserted into the ``grammar_proposals``
table with ``status='pending'``. The two writes are the audit pair:
humans read the file via QuantIQ's dashboard; downstream code reads
the table.

Structurally there is NO ``apply_loosening`` function in this module —
loosenings only flow through ``OPEN_PROPOSALS.md`` and the operator's
``forge grammar apply-proposal`` (Phase 5 module 12). This mirrors the
analogue in ``forge.prefilters.calibration`` where ``apply_tightening``
exists but ``apply_loosening`` does not (hard rule #4).
"""

from __future__ import annotations

import json
import os
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any

import yaml

if TYPE_CHECKING:
    from pathlib import Path

    import duckdb

    from forge.feedback.types import GrammarProposal


CONTRACT_HEADER = "# contract: forge-proposals/v1"


_HEADER_BLOCK = (
    f"{CONTRACT_HEADER}\n"
    "# Generated by Forge auto-tune and human refinement workflows.\n"
    "# Operator approval flow:\n"
    "#   1. Forge appends new PENDING docs to this file.\n"
    "#   2. Operator reviews via QuantIQ dashboard or"
    " `quantiq forge list-proposals`.\n"
    "#   3. Approval/rejection writes a marker JSON to"
    " <approval_inbox>/<id>.{approved,rejected}.json\n"
    "#   4. Forge folds approved changes into config/grammar.yaml on"
    " the next loop.\n"
    "# DO NOT edit `status` lines manually — use the approval flow so"
    " the audit trail is preserved.\n"
)


def _str_representer(
    dumper: yaml.SafeDumper, data: str,
) -> yaml.ScalarNode:
    """Force literal-block style for multi-line strings — keeps
    ``proposal_yaml`` readable instead of quoted-with-newlines."""
    if "\n" in data:
        return dumper.represent_scalar(
            "tag:yaml.org,2002:str", data, style="|",
        )
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


yaml.add_representer(str, _str_representer, Dumper=yaml.SafeDumper)


def _has_v1_header(open_proposals_path: Path) -> bool:
    if not open_proposals_path.exists():
        return False
    try:
        with open_proposals_path.open("r", encoding="utf-8") as fh:
            first = fh.readline()
    except OSError:  # pragma: no cover — file vanished between exists() and open
        return False
    return first.strip() == CONTRACT_HEADER


def _format_v1_document(proposal: GrammarProposal) -> str:
    """Render a GrammarProposal as a v1 YAML mapping doc.

    Returns the YAML body (no leading ``---`` separator); the caller
    composes the full file content.
    """
    doc: dict[str, Any] = {
        "proposal_id": str(proposal.proposal_id),
        "status": "PENDING",
        "proposed_at": proposal.proposed_at.isoformat(),
        "proposal_type": proposal.proposal_type,
        "target": proposal.target,
        "rationale": proposal.rationale,
        "evidence": (
            dict(proposal.evidence_json)
            if proposal.evidence_json
            else {}
        ),
        "proposal_yaml": proposal.proposal_yaml,
    }
    return yaml.safe_dump(
        doc,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )


def _atomic_write(path: Path, content: str) -> None:
    """Write ``content`` to ``path`` atomically (tmp + rename).

    The tmp lives next to the destination so the rename is on the same
    filesystem (POSIX guarantees atomicity).
    """
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, path)


def _compose_new_body(
    existing_text: str, v1_doc: str,
) -> str:
    """Build the full file content after appending ``v1_doc``."""
    if not existing_text:
        return f"{_HEADER_BLOCK}\n---\n{v1_doc.rstrip()}\n"
    return f"{existing_text.rstrip()}\n---\n{v1_doc.rstrip()}\n"


def _insert_grammar_proposals_row(
    db: duckdb.DuckDBPyConnection,
    proposal: GrammarProposal,
) -> None:
    db.execute(
        """
        INSERT INTO grammar_proposals
            (proposal_id, proposed_at, proposal_type, proposal_yaml,
             rationale, evidence_json, status)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        [
            str(proposal.proposal_id),
            proposal.proposed_at,
            proposal.proposal_type,
            proposal.proposal_yaml,
            proposal.rationale,
            json.dumps(proposal.evidence_json, sort_keys=True),
            "pending",
        ],
    )


def _intent_key(evidence: Mapping[str, Any] | None) -> tuple[str, str]:
    """Stable (trigger, detail) pair identifying a proposal's intent.

    Each Forge §8.4 trigger keys its detail differently in evidence:
      - gate_failure_concentration → `target` (the gate_name)
      - hypothesis_dominance / param_no_promotion → `hypothesis`
      - family_dominance → `family`

    Returns ("", "") for proposals lacking a trigger (legacy / hand-crafted)
    — the caller's fallback path keys on rationale instead.
    """
    ev = evidence or {}
    trigger = str(ev.get("trigger", ""))
    detail = str(
        ev.get("target")
        or ev.get("hypothesis")
        or ev.get("family")
        or "",
    )
    return (trigger, detail)


def _has_identical_pending_proposal(
    db: duckdb.DuckDBPyConnection,
    proposal: GrammarProposal,
) -> bool:
    """True if a pending proposal with the same `intent` already exists.

    The auto-tune trigger fires once per batch (§8.4); without dedup, every
    batch where the trigger condition holds appends a new proposal. The
    semantics are identical — same target, same proposed adjustment — so
    writing each one separately just floods OPEN_PROPOSALS.md without
    surfacing new operator information.

    **D034 key change.** Pre-D034 the match key was `(proposal_type,
    rationale)`, but rationale strings embed mutable counts
    ("308 of rejected candidates failed `X`...") that change every batch,
    so the dedup never fired in practice and OPEN_PROPOSALS.md accumulated
    one entry per batch per gate. The fix: match on the proposal's
    structured intent via `_intent_key`. Per-trigger detail keys
    (`target` / `hypothesis` / `family`) capture "what we want the
    operator to decide" without depending on count fields that drift
    across batches.

    Fallback: if either side lacks a `trigger` in evidence_json, fall back
    to the legacy `(proposal_type, rationale)` match for that pair —
    preserves behavior for any historical or hand-crafted proposal.
    """
    target_intent = _intent_key(proposal.evidence_json)
    if target_intent == ("", ""):
        row = db.execute(
            """
            SELECT 1 FROM grammar_proposals
            WHERE proposal_type = ?
              AND rationale = ?
              AND status = 'pending'
            LIMIT 1
            """,
            [proposal.proposal_type, proposal.rationale],
        ).fetchone()
        return row is not None

    rows = db.execute(
        """
        SELECT evidence_json FROM grammar_proposals
        WHERE proposal_type = ? AND status = 'pending'
        """,
        [proposal.proposal_type],
    ).fetchall()
    for (ev_blob,) in rows:
        if isinstance(ev_blob, str):
            try:
                ev = json.loads(ev_blob)
            except json.JSONDecodeError:
                continue
        elif isinstance(ev_blob, dict):
            ev = ev_blob
        else:
            continue
        if _intent_key(ev) == target_intent:
            return True
    return False


def append_proposal(
    proposal: GrammarProposal,
    *,
    open_proposals_path: Path,
    db: duckdb.DuckDBPyConnection,
) -> bool:
    """Append the proposal to OPEN_PROPOSALS.md and insert a pending row.

    Returns ``True`` when the proposal was written, ``False`` when it was
    skipped because an identical pending proposal already exists. The
    skip-write is the structural prevention of OPEN_PROPOSALS.md flooding
    (§8.4 trigger fires every batch; without dedup, an idle weekend
    accumulates 1000+ identical entries).

    Refuses to write to a non-v1 file. Operator must run
    ``backend/scripts/migrate_forge_proposals_to_v1.py`` (in the QuantIQ
    repo) once to convert legacy content; subsequent writes from this
    module preserve the v1 contract.
    """
    if _has_identical_pending_proposal(db, proposal):
        return False

    open_proposals_path.parent.mkdir(parents=True, exist_ok=True)

    if open_proposals_path.exists() and open_proposals_path.stat().st_size > 0:
        if not _has_v1_header(open_proposals_path):
            msg = (
                f"OPEN_PROPOSALS.md at {open_proposals_path} is not in "
                f"contract {CONTRACT_HEADER!r}. Run "
                "backend/scripts/migrate_forge_proposals_to_v1.py "
                "(QuantIQ repo) to convert."
            )
            raise RuntimeError(msg)
        existing_text = open_proposals_path.read_text(encoding="utf-8")
    else:
        existing_text = ""

    v1_doc = _format_v1_document(proposal)
    new_body = _compose_new_body(existing_text, v1_doc)
    _atomic_write(open_proposals_path, new_body)

    _insert_grammar_proposals_row(db, proposal)
    return True


__all__ = ["CONTRACT_HEADER", "append_proposal"]
